spring:
  mail:
    host: smtp-relay.brevo.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  application:
    name: carland_service

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        jdbc:
          batch_size: 32
        order_inserts: true
        order_updates: true

server:
  port: 9091

carland:
  internal-token: ${CARLAND_INTERNAL_TOKEN:}
  webhook:
    signature-secret: ${WEBHOOK_SECRET:}

super:
  admin:
    phone: ${SUPER_ADMIN_PHONE}

hyper:
  auth:
    client-id: ${HYPER_CLIENT_ID}
    client-secret: ${HYPER_CLIENT_SECRET}
    base-url: https://api.hyper.az
    token-url: /partner/v1/oauth/token

brevo:
  api-key: ${BREVO_API_KEY}